### ISSUE TITLE
Support Intel Pro wireless network card (module ipw2200 + firmware)

### ISSUE THREAD

**Issue by erikmack** [Arachnid/netboot.me#17]
1. Burn iso to CD
2. Boot from netboot.me CD
   Expected: network reached, other awesomeness
   Actual: Failure with 'no network device found', boot screen is hung requiring hard reboot

The Intel Pro Wireless driver is in the kernel (module ipw2200).  IIRC, it is required to be a module (not statically linked), and there is also separate proprietary firmware required.  isolinux-based images (Gentoo installer, etc) find this card.

If I can help be a guinea pig for fixing this issue, please let me know.  It looks like it could be a great service.  I've been looking for something like this, and unetbootin nearly destroyed my system recently :-)

Many thanks,
Erik

**Comment by arodland** [comment]
The preboot environment is gPXE, not Linux, so ipw2200 won't help. gPXE currently has very limited support for wireless cards, although it is a work in progress.

**Comment by Arachnid** [comment]
As adroland says - but there is a GSoC project to add wireless support to gPXE.
