### ISSUE TITLE
version check on gPXE doesn't even look at gPXE's version.

### ISSUE THREAD

**Issue by Docteh** [Arachnid/netboot.me#20]
gPXE is getting closed to version 1.0.0 and if a person tries to boot from http://netboot.me with a copy of gPXE that doesn't report "(netboot.me/0.1.1)" in the user agent, a message "Your copy of gPXE is too old. Upgrade at netboot.me to avoid seeing this every boot!" pops up and gPXE 0.9.7+ is chain loaded.

**Comment by Chaz6** [comment]
gPXE 1.0.0 is now released!
