### ISSUE TITLE
Karmic (9.10) amd64 rescue config

### ISSUE THREAD

**Issue by llloic** [Arachnid/netboot.me#24]
Hi,

I have created a Karmic (9.10) amd64 rescue configuration, which I found usefull after having installed an amd64 Karmic and wanting to move the root partition. Maybe it could be added in the standard menu along with the Karmic x86 rescue configuration

http://www.netboot.me/64001

Best regards.

**Comment by Arachnid** [comment]
Done, thank you.

**Comment by Arachnid** [comment]
Done, thank you.
