### ISSUE TITLE
Added Ubuntu Lucid Lynx 10.04 (LTS) Installers

### ISSUE THREAD

**Issue by dotwaffle** [Arachnid/netboot.me#27]
As requested, I've created some new Ubuntu installer configs, if they could be incorporated in the menu system, I'd be very grateful:

i386: http://netboot.me/149001
amd64: http://www.netboot.me/147002

If you're struggling to find time or resources to run the project, give me a shout - I'm more than willing to help out, be it server space, general config maintenance or just the occasional encouragement over a beer ;)

**Comment by Tomo59** [comment]
Thank you for the configs ! 

Indeed, it would be great if they were incorporated in the menu...

**Comment by Arachnid** [comment]
Sorry I took so long to respond to this. I've added Ubuntu images to the menu.

If you or anyone else are interested in taking over day-to-day maintenance of netboot.me, do let me know, as I lack time recently. Day to day maintenance consists of adding new images (and testing them), removing old ones, and possibly updating the boot image with new features and new releases of gPXE.

**Comment by dotwaffle** [comment]
I'd love to help out where possible - I've emailed you with my details.
