### ISSUE TITLE
Downloading of linux images is too slow...

### ISSUE THREAD

**Issue by Harvie** [Arachnid/netboot.me#39]
Hello.
netboot.me is working perfectly for me, but downloading is unbelievably slow.

This is my NIC:

```
[00:28:58] 0 ;) harvie@insomnia WL500GPv2 $ lspci | grep -i ether
00:04.0 Ethernet controller: Silicon Integrated Systems [SiS] SiS900 PCI Fast Ethernet (rev 91)
```

Speedtest.net says that i have ~10Mbps download speed with archlinux booted. Booting (downloading) Tiny Core Linux (~8000k) from netboot.me  takes ~3-5 minutes. Booting SliTaz (~30M) is unbeleivably slow, so i've never managed to boot it (i terminated it because it was too slow). I can't imagine that i can use this to install Linux on multiple machines quickly. Are you experiencing same speed issues or it's my local issue?

**Comment by Arachnid** [comment]
Unfortunately, this is down to gPXE's TCP stack - it's seriously sub-optimal, and seems to be worse on some controllers than others. There's nothing I can do about it unless they improve their network stack.

**Comment by Harvie** [comment]
What about downloading small linux image and using it to download bigger file?
What about using TCP stack of TFTP client in NIC's ROM/BIOS? (Which means use TFTP directly instead of gPXE)

**Comment by arodland** [comment]
Hmm, there actually is a possibility of using Linux to chain-load Linux using a ramdisk and kexec, but I'm not sure how small the required initramfs would be once it included every reasonable network driver.

Still, if you think it's worthwhile, write it! :)

**Comment by isomer** [comment]
Improving gPXE's networking stack shouldn't be impossible, even just increasing the default tcp window size is likely to help.

**Comment by Harvie** [comment]
Arachnid, isomer: there is already fork: https://github.com/Arachnid/netboot.me-gpxe can it be edited there?

**Comment by packetcollision** [comment]
This is only a workaround, but in my case booting slitaz over the internet takes about 45 minutes, but downloading the iso to a local server takes 45 seconds, and then with the proper DNS overrides (a local BIND server pretending to be the master for mirror.slitaz.org and pointing it to a local server), slitaz boots almost instantly. I'm using a 500Mhz VIA Samuel2 thin-client with a VIA Rhine II onboard network card.

**Comment by arodland** [comment]
@packetcollision that makes sense ­— the simplistic TCP stack isn't able to increase the window size beyond the minimum, so transfers get very slow at high latency. At low latency, the window has a smaller effect so the download is fast.
