### ISSUE TITLE
Updated linux distros

### ISSUE THREAD

**Issue by mogorman** [Arachnid/netboot.me#41]
Fedora 17 Installer (x86)    http://www.netboot.me/641002
Debian Squeeze (6.0) Installer (x86)   http://www.netboot.me/646001
Ubuntu Precise (12.04) Installer (amd64) http://www.netboot.me/646002
Debian Squeeze (6.0) Installer (amd64) http://www.netboot.me/647001
Fedora 17 Installer (amd64) http://www.netboot.me/648001
CentOS 6.2 Installer (i386) http://www.netboot.me/649001
CentOS 6.2 Installer (amd64)    http://www.netboot.me/650001
Ubuntu Precise (12.04) Installer (x86) http://www.netboot.me/651001

all tested.  id be happy do more of them if they were going to be rolled into default code base

**Comment by woeisme** [comment]
I've tested lenny debian installer(amd64)  using KVM and booting failed. 
I think the flaw here is that you're using a path that points to specific distro names (wheezy, lenny, squeeze) instead of pointing to their aliases (testing, unstable, stable) which would work better long term.

**Comment by mogorman** [comment]
Closing as it's been 6 years.
