### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by yurijevs** [Arachnid/netboot.me#45]
NOTICE: This domain name expired on 08/14/2013 and is pending renewal or deletion.

**Comment by Arachnid** [comment]
Argh. Fixed. netboot.me is not under active development - I'm looking for an alternate maintainer - but I didn't intend to let the registration lapse.

**Comment by porelli** [comment]
Again, new domain status is: REDEMPTIONPERIOD

**Comment by Arachnid** [comment]
Fixed, thanks.
